### PR TITLE
try/catch JSON.parse

### LINKED ISSUE #5: JSON.parse errors creates uncatchable error
Hello,

There are a couple ```JSON.parse``` calls in async functions that aren't in try/catch blocks. If JSON.parse results in an error (i.e. the file is corrupt), then an uncatchable error is thrown that will crash the calling process.

PR incoming.

### PR DESCRIPTION
**Pull request by timbowhite**
fixes #5

### CODE REVIEW

**Comment by smamczak** [comment]
can this be merge please?

**Comment by noriellecruz** [comment]
this should be merged

**Review by LionC — APPROVED** [review]
LGTM

**Comment by LionC** [comment]
Will do a release tonight

**Comment by LionC** [comment]
Published a new version with that patch

**Pull request merged**
